version: '3.9'

services:
  ecr-scan:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INPUT_REPOSITORY=newcross/asklepius/nc-vendors-service
      - INPUT_TAG=latest
      - INPUT_FAIL_THRESHOLD=critical
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

  #ecr-scan:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  environment:
  #    - INPUT_REPOSITORY=my-ord/my-service
  #    - INPUT_TAG=latest
  #    - INPUT_FAIL_THRESHOLD=critical
  #    - AWS_REGION=eu-west-2
  #    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #    - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}